version: '3.8'

services:
  backend:
    build:
      context: ../backend/.
      target: development
    ports:
      - '4000:4000'
    env_file: ../backend/.env
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - MONGO_URI=mongodb://root:example@mongo:27017/forum?authSource=admin
    depends_on:
      - mongo
      - redis
      - mongo-express
    volumes:
      - ../backend:/backend
      - /backend/node_modules
    command: npm run dev
  react-ui:
    build:
      context: ../frontend
      target: development
    environment:
      - NODE_ENV=development
    ports:
      - '5173:5173'
    container_name: react-ui
    stdin_open: true
    volumes:
      - ../frontend:/frontend
      - /frontend/node_modules

    command: npm run dev
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
